server:
  port: 8080
  servlet.context-path: /api/mail

spring:
  mail:
    host: ${MMS_HOST}
    protocol: smtp
    port: ${MMS_PORT}
    username: ${MMS_USERNAME}
    password: ${MMS_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mms:
  sender: ${MMS_SENDER}
  recipient: ${MMS_RECIPIENT}
