name: CI and Deploy

on: push

jobs:
  maven:
    name: Build MMS with Maven
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: actions/cache@v3
        env:
          cache-name: m2
        with:
          path: /home/runner/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - uses: actions/upload-artifact@v3
        with:
          name: mms-target
          path: target

  docker:
    name: Build MMS Docker image
    runs-on: ubuntu-latest
    needs: maven
    if: startsWith(github.ref, 'refs/tags/v1.')

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: mms-target
          path: target

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && ls -al . target

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: leonmydla/mms:latest,leonmydla/mms:${{ env.RELEASE_VERSION }}
          push: true
