name: CI and Deploy

on: push

jobs:
  test:
    name: Build MMS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: actions/cache@v2
        env:
          cache-name: m2
        with:
          path: /home/runner/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: name
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v1.')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build docker image
        if: startsWith(github.ref, 'refs/tags/v1.')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leonmydla/mms:${{ github.ref }}
